# Generated by Django 5.1.5 on 2025-01-22 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message={'en': "Phone number must be entered in the format: '+995XXXXXXXXX'.", 'ka': "ტელეფონის ნომერი უნდა იყოს ფორმატში: '+995XXXXXXXXX'"}, regex='^\\+995\\d{9}$')]),
        ),
    ]
