name: Deploy to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Server
              run: |
                  ssh -o StrictHostKeyChecking=no -t root@64.227.36.23 <<EOF
                  git config --global --add safe.directory /var/www/dance_project
                  cd /var/www/dance_project
                  git pull origin main
                  source venv/bin/activate
                  pip install -r requirements.txt
                  python manage.py migrate
                  python manage.py collectstatic --noinput
                  sudo systemctl restart gunicorn
                  EOF
