# Generated by Django 5.1.5 on 2025-04-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(default='1', max_length=255, unique=True)),
                ('name_en', models.CharField(default='1', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('description_ka', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('school_name_ka', models.CharField(blank=True, max_length=255, null=True)),
                ('school_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('promoted', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('with_discount', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.courseauthor')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ka', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_ka', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField()),
                ('demo', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
