# Generated by Django 5.1.5 on 2025-01-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('description_ka', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('school_name_ka', models.CharField(blank=True, max_length=255, null=True)),
                ('school_name_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.courseauthor'),
            preserve_default=False,
        ),
    ]
