# Generated by Django 5.1.5 on 2025-01-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_courseauthor_category_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseauthor',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseauthor',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseauthor',
            name='with_discount',
            field=models.BooleanField(default=False),
        ),
    ]
