# Generated by Django 5.1.5 on 2025-04-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name_en_alter_category_name_ka'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='courseauthor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='courseauthor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='courseauthor',
            name='category',
        ),
        migrations.AddField(
            model_name='courseauthor',
            name='category',
            field=models.ManyToManyField(to='products.category'),
        ),
    ]
