# Generated by Django 5.1.5 on 2025-01-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_courseauthor_is_new_courseauthor_promoted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ka', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_ka', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField()),
                ('demo', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
