# Generated by Django 5.1.5 on 2025-01-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_videocontent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name_ka', 'author')},
        ),
    ]
