# Generated by Django 5.1.5 on 2025-01-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name_ka', 'category')},
        ),
    ]
