# Generated by Django 5.1.5 on 2025-05-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_course_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecommentvotes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.coursecommentvotes'),
        ),
        migrations.AlterField(
            model_name='coursecommentvotes',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.coursecommentvotes'),
        ),
    ]
