# Generated by Django 5.1.5 on 2025-05-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_coursecommentvotes_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='discount_price',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='price',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
