# Generated by Django 5.1.5 on 2025-06-01 20:12

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_videocontent_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='video_thumbnails/'),
        ),
    ]
