# Generated by Django 5.1.5 on 2025-09-25 19:02

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_coursevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='image_url',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='video_image_url/'),
        ),
    ]
