# Generated by Django 5.1.5 on 2026-02-11 17:15

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_videocontent_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='media_assets/')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
