# Generated by Django 5.1.5 on 2026-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
